<h1>Welcome to our newsletter</h1>

<h3>You have registered with the e-mail <?= $entity->email ?> at <?= $entity->created->format('m/d/Y H:i') ?></h3>

<p>
    <span>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde nostrum adipisci soluta necessitatibus repellendus ullam odio quia dicta similique fugiat, possimus nesciunt enim explicabo dolorum dignissimos iste! Dolorum, autem id!</span><span>Commodi quis praesentium ab nemo natus voluptatum rerum? Ipsam obcaecati neque unde pariatur, quis distinctio omnis! Voluptates veritatis ullam accusamus obcaecati necessitatibus in doloribus repudiandae molestiae sunt minima, illum ut.</span><span>Dicta, non consequuntur. Vero asperiores voluptates quidem! Ab repudiandae laborum fugiat assumenda sapiente labore nesciunt ad officia odit, consequatur eius unde culpa veritatis consequuntur consectetur dolorum illo dolore quisquam animi.</span><span>Porro harum ut cum minus! Reprehenderit nostrum ipsam itaque ipsum quia nam, voluptatibus, quod molestiae commodi vitae veritatis placeat numquam. Deserunt a qui aut quam commodi. Repellendus fugit est facilis!</span>
    <span>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde nostrum adipisci soluta necessitatibus repellendus ullam odio quia dicta similique fugiat, possimus nesciunt enim explicabo dolorum dignissimos iste! Dolorum, autem id!</span><span>Commodi quis praesentium ab nemo natus voluptatum rerum? Ipsam obcaecati neque unde pariatur, quis distinctio omnis! Voluptates veritatis ullam accusamus obcaecati necessitatibus in doloribus repudiandae molestiae sunt minima, illum ut.</span><span>Dicta, non consequuntur. Vero asperiores voluptates quidem! Ab repudiandae laborum fugiat assumenda sapiente labore nesciunt ad officia odit, consequatur eius unde culpa veritatis consequuntur consectetur dolorum illo dolore quisquam animi.</span><span>Porro harum ut cum minus! Reprehenderit nostrum ipsam itaque ipsum quia nam, voluptatibus, quod molestiae commodi vitae veritatis placeat numquam. Deserunt a qui aut quam commodi. Repellendus fugit est facilis!</span>
    <span>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde nostrum adipisci soluta necessitatibus repellendus ullam odio quia dicta similique fugiat, possimus nesciunt enim explicabo dolorum dignissimos iste! Dolorum, autem id!</span><span>Commodi quis praesentium ab nemo natus voluptatum rerum? Ipsam obcaecati neque unde pariatur, quis distinctio omnis! Voluptates veritatis ullam accusamus obcaecati necessitatibus in doloribus repudiandae molestiae sunt minima, illum ut.</span><span>Dicta, non consequuntur. Vero asperiores voluptates quidem! Ab repudiandae laborum fugiat assumenda sapiente labore nesciunt ad officia odit, consequatur eius unde culpa veritatis consequuntur consectetur dolorum illo dolore quisquam animi.</span><span>Porro harum ut cum minus! Reprehenderit nostrum ipsam itaque ipsum quia nam, voluptatibus, quod molestiae commodi vitae veritatis placeat numquam. Deserunt a qui aut quam commodi. Repellendus fugit est facilis!</span>
    <span>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde nostrum adipisci soluta necessitatibus repellendus ullam odio quia dicta similique fugiat, possimus nesciunt enim explicabo dolorum dignissimos iste! Dolorum, autem id!</span><span>Commodi quis praesentium ab nemo natus voluptatum rerum? Ipsam obcaecati neque unde pariatur, quis distinctio omnis! Voluptates veritatis ullam accusamus obcaecati necessitatibus in doloribus repudiandae molestiae sunt minima, illum ut.</span><span>Dicta, non consequuntur. Vero asperiores voluptates quidem! Ab repudiandae laborum fugiat assumenda sapiente labore nesciunt ad officia odit, consequatur eius unde culpa veritatis consequuntur consectetur dolorum illo dolore quisquam animi.</span><span>Porro harum ut cum minus! Reprehenderit nostrum ipsam itaque ipsum quia nam, voluptatibus, quod molestiae commodi vitae veritatis placeat numquam. Deserunt a qui aut quam commodi. Repellendus fugit est facilis!</span>
</p>
